### PR TITLE
Packaging with setuptools

### PR DESCRIPTION
**Pull request by solidsnack**
Please find attached changes which enable packaging (and upload) of `cfviz` with setuptools. Please let me know if you would prefer that I upload the package; I am happy to handle that for you.

What are your thoughts on a license?

I think that we should separate printing from rendering -- or at least allow a handle to be passed for rendering -- so that `cfviz` can better function as a Python module as well as a command line program.

### CODE REVIEW

**Comment by benbc** [comment]
@solidsnack Are you still interested in these changes? I've just discovered that I had my Github notifications configured wrongly.

**Comment by lwoodson** [comment]
@benbc I am interested in these changes.

**Comment by nicr9** [comment]
Since this PR can't be merged, I've created an updated PR with rebased changes that should work #7

**Comment by benbc** [comment]
This has been implemented in #7.

**Pull request closed without merging**
